import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { DesktopNavbar } from "./components/Navbar";
import "swiper/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Providers>
          <main className="bg-main-bg bg-no-repeat bg-fixed bg-cover w-full min-h-screen">
            <DesktopNavbar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
